sudo: required
language: generic
services:
    -docker
    
before_install:
    - docker build -t prawinpraba/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true prawinpraba/react-test npm test -- --coverage 

after_success:
    - docker build -t prawinpraba/multi-client ./client
    - docker build -t prawinpraba/multi-nginx ./nginx
    - docker build -t prawinpraba/multi-server ./server
    - docker build -t prawinpraba/multi-worker ./worker

- echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin 
- docker push prawinpraba/multi-client
- docker push prawinpraba/multi-nginx
- docker push prawinpraba/multi-server
- docker push prawinpraba/multi-worker